name: itkwidgets
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - nodejs
  - pyimagej
  - pip:
    - itk>=5.3.0
    - itkwidgets[all]>=1.0a24
    - imjoy-elfinder
    - imjoy-jupyter-extension
    - imjoy-jupyterlab-extension
    - monai-weekly[nibabel, matplotlib, tqdm]
    - imageio
    - pyvista
    - dask[diagnostics]
    - toolz
    - scikit-image
    - pooch
    - matplotlib
    - tqdm
    - vtk
    - netCDF4
    - xarray
    - zarr
    - fsspec[http]
