name: itkwidgets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - itk
  - pip
  - pip:
    - ipywidgets>=7.1.2
    - numpy
    - six
    - zstandard
    - ipywebrtc
    - bqplot
    - plotly>=3.3.0
